export const MAPS =
    [
        {
        id: 0,
        name: "de_inferno",
        image: "./mapthumbnails/de_inferno.jpg",
        label: "select",
        key: "de_inferno",
        },
        {
        id: 1,
        name: "de_vertigo",
        image: "./mapthumbnails/de_vertigo.jpg",
        label: "select",
        key: "de_vertigo",
        },
        {
        id: 2,
        name: "de_mirage",
        image: "./mapthumbnails/de_mirage.jpg",
        label: "select",
        key: "de_mirage",
        },
        {
        id: 3,
        name: "de_train",
        image: "./mapthumbnails/de_train.jpg",
        label: "select",
        key: "de_train",
        },
        {
        id: 4,
        name: "de_dust2",
        image: "./mapthumbnails/de_dust2.jpg",
        label: "select",
        key: "de_dust2",
        },
        {
        id: 5,
        name: "de_cbble",
        image: "./mapthumbnails/de_cbble.jpg",
        label: "select",
        key: "de_cbble",
        },
        {
        id: 6,
        name: "de_cache",
        image: "./mapthumbnails/de_cache.jpg",
        label: "select",
        key: "de_cache",
        },
        {
        id: 7,
        name: "de_nuke",
        image: "./mapthumbnails/de_nuke.jpg",
        label: "select",
        key: "de_nuke",
        },
        {
        id: 8,
        name: "de_overpass",
        image: "./mapthumbnails/de_overpass.jpg",
        label: "select",
        key: "de_overpass",
        },
        {
        id: 9,
        name: "de_season",
        image: "./mapthumbnails/de_season.jpg",
        label: "select",
        key: "de_season",
        },
        {
        id: 10,
        name: "cs_office",
        image: "./mapthumbnails/cs_office.jpg",
        label: "select",
        key: "cs_office",
        },
        {
        id: 11,
        name: "de_toscan",
        image: "./mapthumbnails/de_tuscan.jpg",
        label: "select",
        key: "de_toscan",
        }
    ];